### ISSUE TITLE
Deploy following the wiki deploy section don't work.

### ISSUE THREAD

**Issue by nmorono** [openshift/must-gather-operator#69]
I was trying to install following the wiki deploy instructions and didn't work.

```shell
git clone git@github.com:openshift/must-gather-operator.git; cd must-gather-operator
oc apply -f deploy/crds/managed.openshift.io_mustgathers_crd.yaml          <<< Bad file name
oc new-project must-gather-operator
oc -n must-gather-operator apply -f deploy          <<< Bad NS name.
```

**Comment by fahlmant** [comment]
The file name is a typo in the README and can be fixed. 

What's wrong with the namespace? Its created when running `oc new-project must-gather-operator`. Make sure the namespace exists before running `oc -n must-gather-operator apply -f deploy`
